web:
  image: nginx:latest
  restart: always
  environment:
    SERVICE_80_NAME: ${POD_NAME}/http
  volumes_from:
    - data
  ports:
    - 80

data:
  build: .
  command: tail -f /dev/null
  restart: always
